//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMSEntities : DbContext
    {
        public BMSEntities()
            : base("name=BMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetType> BudgetTypes { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Financial_Year> Financial_Year { get; set; }
        public virtual DbSet<Head_Master> Head_Master { get; set; }
        public virtual DbSet<Mst_ApproveType> Mst_ApproveType { get; set; }
        public virtual DbSet<Mst_Assign_Designation> Mst_Assign_Designation { get; set; }
        public virtual DbSet<Mst_AssignCircleDivison> Mst_AssignCircleDivison { get; set; }
        public virtual DbSet<Mst_AssignUnitToBank> Mst_AssignUnitToBank { get; set; }
        public virtual DbSet<Mst_AssignZoneCircle> Mst_AssignZoneCircle { get; set; }
        public virtual DbSet<Mst_Bank> Mst_Bank { get; set; }
        public virtual DbSet<Mst_BnkDtls> Mst_BnkDtls { get; set; }
        public virtual DbSet<Mst_Capital_Works_Detail> Mst_Capital_Works_Detail { get; set; }
        public virtual DbSet<Mst_Circle> Mst_Circle { get; set; }
        public virtual DbSet<Mst_Country> Mst_Country { get; set; }
        public virtual DbSet<Mst_District> Mst_District { get; set; }
        public virtual DbSet<Mst_Divison> Mst_Divison { get; set; }
        public virtual DbSet<Mst_InnerSubHead> Mst_InnerSubHead { get; set; }
        public virtual DbSet<Mst_month> Mst_month { get; set; }
        public virtual DbSet<Mst_SalaryHeads> Mst_SalaryHeads { get; set; }
        public virtual DbSet<Mst_State> Mst_State { get; set; }
        public virtual DbSet<Mst_Unit> Mst_Unit { get; set; }
        public virtual DbSet<Mst_Zone> Mst_Zone { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tarn_Add_Budget> Tarn_Add_Budget { get; set; }
        public virtual DbSet<Tran_Cap_TP_Budget> Tran_Cap_TP_Budget { get; set; }
        public virtual DbSet<Tran_CWRequistionNumber> Tran_CWRequistionNumber { get; set; }
        public virtual DbSet<Tran_User_Creation> Tran_User_Creation { get; set; }
        public virtual DbSet<Trans_Additional_Allotment> Trans_Additional_Allotment { get; set; }
        public virtual DbSet<Trans_Additional_allotment_Work> Trans_Additional_allotment_Work { get; set; }
        public virtual DbSet<Trans_Cap_Work_Bgt_Requsion_Unit> Trans_Cap_Work_Bgt_Requsion_Unit { get; set; }
        public virtual DbSet<Trans_Cap_Work_Budget> Trans_Cap_Work_Budget { get; set; }
        public virtual DbSet<Trans_Cap_Wrk_CashRequistionInvoice> Trans_Cap_Wrk_CashRequistionInvoice { get; set; }
        public virtual DbSet<Trans_Capital_TPBgt_Prop_By_Unit> Trans_Capital_TPBgt_Prop_By_Unit { get; set; }
        public virtual DbSet<Trans_CashRequistionInvoice> Trans_CashRequistionInvoice { get; set; }
        public virtual DbSet<Trans_CashRequstionNonInvoice> Trans_CashRequstionNonInvoice { get; set; }
        public virtual DbSet<Trans_Cptl_wrk_CashRequstionNonInvoice> Trans_Cptl_wrk_CashRequstionNonInvoice { get; set; }
        public virtual DbSet<Trans_LeveL_ApprovalInvoice> Trans_LeveL_ApprovalInvoice { get; set; }
        public virtual DbSet<Trans_LeveL_ApprovalNonInvoice> Trans_LeveL_ApprovalNonInvoice { get; set; }
        public virtual DbSet<Trans_RequsitionNumber> Trans_RequsitionNumber { get; set; }
        public virtual DbSet<Trans_Revnu_Expenditure_By_Unit> Trans_Revnu_Expenditure_By_Unit { get; set; }
        public virtual DbSet<TransCap_Wrk__LeveL_ApprovalInvoice> TransCap_Wrk__LeveL_ApprovalInvoice { get; set; }
        public virtual DbSet<TransCap_Wrk__LeveL_ApprovalNonInvoice> TransCap_Wrk__LeveL_ApprovalNonInvoice { get; set; }
        public virtual DbSet<Trns_Chng_Pwd_Log> Trns_Chng_Pwd_Log { get; set; }
        public virtual DbSet<Mst_User> Mst_User { get; set; }
        public virtual DbSet<Mst_Department> Mst_Department { get; set; }
        public virtual DbSet<Mst_Designation> Mst_Designation { get; set; }
        public virtual DbSet<Trans_Salary> Trans_Salary { get; set; }
        public virtual DbSet<Mst_SubHead> Mst_SubHead { get; set; }
        public virtual DbSet<Trans_Assign_User_ToApprov> Trans_Assign_User_ToApprov { get; set; }
    
        public virtual ObjectResult<Head_MasterSelectAll_Result> Head_MasterSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Head_MasterSelectAll_Result>("Head_MasterSelectAll");
        }
    
        public virtual ObjectResult<BankDetails_SelectAll_Result> BankDetails_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BankDetails_SelectAll_Result>("BankDetails_SelectAll");
        }
    
        public virtual ObjectResult<SubHeadMasterAll_Result> SubHeadMasterAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubHeadMasterAll_Result>("SubHeadMasterAll");
        }
    
        public virtual ObjectResult<User_Create_Details_Result> User_Create_Details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User_Create_Details_Result>("User_Create_Details");
        }
    
        public virtual ObjectResult<StateSelectAll_Result> StateSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StateSelectAll_Result>("StateSelectAll");
        }
    
        public virtual ObjectResult<DistrictSelectAll_Result> DistrictSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DistrictSelectAll_Result>("DistrictSelectAll");
        }
    
        public virtual ObjectResult<AssignCircleDivisonAll_Result> AssignCircleDivisonAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AssignCircleDivisonAll_Result>("AssignCircleDivisonAll");
        }
    
        public virtual ObjectResult<AssignUnitBankAll_Result> AssignUnitBankAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AssignUnitBankAll_Result>("AssignUnitBankAll");
        }
    
        public virtual ObjectResult<AssigneToUser_SelectAll_Result> AssigneToUser_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AssigneToUser_SelectAll_Result>("AssigneToUser_SelectAll");
        }
    
        public virtual ObjectResult<User_SelectById_Result> User_SelectById(Nullable<int> usr_Id)
        {
            var usr_IdParameter = usr_Id.HasValue ?
                new ObjectParameter("Usr_Id", usr_Id) :
                new ObjectParameter("Usr_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User_SelectById_Result>("User_SelectById", usr_IdParameter);
        }
    
        public virtual ObjectResult<SelectAllByUnitAll_Result> SelectAllByUnitAll(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllByUnitAll_Result>("SelectAllByUnitAll", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual int Update_BudgetexpByUnit(string pXMLTABLEEARNING, Nullable<int> addBy, Nullable<int> rv, ObjectParameter returnValue)
        {
            var pXMLTABLEEARNINGParameter = pXMLTABLEEARNING != null ?
                new ObjectParameter("PXMLTABLEEARNING", pXMLTABLEEARNING) :
                new ObjectParameter("PXMLTABLEEARNING", typeof(string));
    
            var addByParameter = addBy.HasValue ?
                new ObjectParameter("AddBy", addBy) :
                new ObjectParameter("AddBy", typeof(int));
    
            var rvParameter = rv.HasValue ?
                new ObjectParameter("rv", rv) :
                new ObjectParameter("rv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_BudgetexpByUnit", pXMLTABLEEARNINGParameter, addByParameter, rvParameter, returnValue);
        }
    
        public virtual int Update_CapitalTPBudgetByUnit(string pXMLTABLEEARNING, Nullable<int> addBy, Nullable<int> rv, ObjectParameter returnValue)
        {
            var pXMLTABLEEARNINGParameter = pXMLTABLEEARNING != null ?
                new ObjectParameter("PXMLTABLEEARNING", pXMLTABLEEARNING) :
                new ObjectParameter("PXMLTABLEEARNING", typeof(string));
    
            var addByParameter = addBy.HasValue ?
                new ObjectParameter("AddBy", addBy) :
                new ObjectParameter("AddBy", typeof(int));
    
            var rvParameter = rv.HasValue ?
                new ObjectParameter("rv", rv) :
                new ObjectParameter("rv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_CapitalTPBudgetByUnit", pXMLTABLEEARNINGParameter, addByParameter, rvParameter, returnValue);
        }
    
        public virtual int UpdateBudgetexpByUnit(string pXMLTABLEEARNING, Nullable<int> addBy, Nullable<int> rv, ObjectParameter returnValue)
        {
            var pXMLTABLEEARNINGParameter = pXMLTABLEEARNING != null ?
                new ObjectParameter("PXMLTABLEEARNING", pXMLTABLEEARNING) :
                new ObjectParameter("PXMLTABLEEARNING", typeof(string));
    
            var addByParameter = addBy.HasValue ?
                new ObjectParameter("AddBy", addBy) :
                new ObjectParameter("AddBy", typeof(int));
    
            var rvParameter = rv.HasValue ?
                new ObjectParameter("rv", rv) :
                new ObjectParameter("rv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBudgetexpByUnit", pXMLTABLEEARNINGParameter, addByParameter, rvParameter, returnValue);
        }
    
        public virtual ObjectResult<BudgetSelectAll_Result> BudgetSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BudgetSelectAll_Result>("BudgetSelectAll");
        }
    
        public virtual ObjectResult<SelectAllByUnitAllbyId_Result> SelectAllByUnitAllbyId(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllByUnitAllbyId_Result>("SelectAllByUnitAllbyId", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual ObjectResult<SelectAllByUnitAllbyIdd_Result> SelectAllByUnitAllbyIdd(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllByUnitAllbyIdd_Result>("SelectAllByUnitAllbyIdd", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual ObjectResult<GetAllRevenueHeadForFstLvl_Result> GetAllRevenueHeadForFstLvl(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllRevenueHeadForFstLvl_Result>("GetAllRevenueHeadForFstLvl", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual ObjectResult<ExpenditureSelectAllByUnit_Result> ExpenditureSelectAllByUnit(Nullable<int> fin_Id, Nullable<int> unit_Id, Nullable<int> head_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            var head_IdParameter = head_Id.HasValue ?
                new ObjectParameter("Head_Id", head_Id) :
                new ObjectParameter("Head_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpenditureSelectAllByUnit_Result>("ExpenditureSelectAllByUnit", fin_IdParameter, unit_IdParameter, head_IdParameter);
        }
    
        public virtual ObjectResult<GetAllRevenueHeadForSecLvl_Result> GetAllRevenueHeadForSecLvl(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllRevenueHeadForSecLvl_Result>("GetAllRevenueHeadForSecLvl", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual ObjectResult<ExpendSelectAllForHoApprove_Result> ExpendSelectAllForHoApprove(Nullable<int> fin_Id, Nullable<int> unit_Id, Nullable<int> head_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            var head_IdParameter = head_Id.HasValue ?
                new ObjectParameter("Head_Id", head_Id) :
                new ObjectParameter("Head_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpendSelectAllForHoApprove_Result>("ExpendSelectAllForHoApprove", fin_IdParameter, unit_IdParameter, head_IdParameter);
        }
    
        public virtual ObjectResult<RevenueBudgetSelectAllHead_Result> RevenueBudgetSelectAllHead(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RevenueBudgetSelectAllHead_Result>("RevenueBudgetSelectAllHead", fin_IdParameter, unit_IdParameter);
        }
    
        public virtual ObjectResult<ExpenditureSelectAllByUnitForFinal_Result> ExpenditureSelectAllByUnitForFinal(Nullable<int> fin_Id, Nullable<int> unit_Id, Nullable<int> head_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            var head_IdParameter = head_Id.HasValue ?
                new ObjectParameter("Head_Id", head_Id) :
                new ObjectParameter("Head_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExpenditureSelectAllByUnitForFinal_Result>("ExpenditureSelectAllByUnitForFinal", fin_IdParameter, unit_IdParameter, head_IdParameter);
        }
    
        public virtual ObjectResult<GetRevenueHeadforProposalByUnit_Result> GetRevenueHeadforProposalByUnit(Nullable<int> fin_Id, Nullable<int> unit_Id)
        {
            var fin_IdParameter = fin_Id.HasValue ?
                new ObjectParameter("Fin_Id", fin_Id) :
                new ObjectParameter("Fin_Id", typeof(int));
    
            var unit_IdParameter = unit_Id.HasValue ?
                new ObjectParameter("Unit_Id", unit_Id) :
                new ObjectParameter("Unit_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRevenueHeadforProposalByUnit_Result>("GetRevenueHeadforProposalByUnit", fin_IdParameter, unit_IdParameter);
        }
    }
}
