//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head_Master
    {
        public int Head_Id { get; set; }
        public string hdnm { get; set; }
        public string hdcode { get; set; }
        public Nullable<int> BugtTyp_Id { get; set; }
        public Nullable<System.DateTime> addon { get; set; }
        public Nullable<int> addby { get; set; }
        public Nullable<System.DateTime> modon { get; set; }
        public Nullable<int> modby { get; set; }
        public bool isdelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
