//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_month
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_month()
        {
            this.Trans_Salary = new HashSet<Trans_Salary>();
        }
    
        public int monthid { get; set; }
        public string monthnm { get; set; }
        public Nullable<System.DateTime> addon { get; set; }
        public Nullable<int> addby { get; set; }
        public Nullable<System.DateTime> modon { get; set; }
        public Nullable<int> modby { get; set; }
        public bool isdelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trans_Salary> Trans_Salary { get; set; }
    }
}
