//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_User
    {
        public int userid { get; set; }
        public Nullable<int> unid { get; set; }
        public Nullable<short> utyp { get; set; }
        public int roleid { get; set; }
        public string empnm { get; set; }
        public string unm { get; set; }
        public string pwd { get; set; }
        public string mail { get; set; }
        public string phn { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
    }
}
