//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Assign_Designation
    {
        public int AssDeg_ID { get; set; }
        public Nullable<int> Desg_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public Nullable<int> Modby { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
