//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Capital_Works_Detail
    {
        public int Cap_Wok_Head_Id { get; set; }
        public string Proj_Name { get; set; }
        public string Proj_Code { get; set; }
        public string Aprov_No { get; set; }
        public Nullable<System.DateTime> Aprov_Date { get; set; }
        public Nullable<decimal> Aprov_Cost { get; set; }
        public Nullable<decimal> Cont_Value { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public Nullable<int> Modby { get; set; }
    }
}
