//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int pageid { get; set; }
        public string distext { get; set; }
        public string tooltip { get; set; }
        public string targeturl { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> orderby { get; set; }
        public Nullable<int> addby { get; set; }
        public Nullable<System.DateTime> addon { get; set; }
        public Nullable<int> modby { get; set; }
        public Nullable<System.DateTime> modon { get; set; }
        public bool isactive { get; set; }
        public Nullable<bool> isdelete { get; set; }
    }
}
