//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int permid { get; set; }
        public int roleid { get; set; }
        public int pageid { get; set; }
        public Nullable<bool> canview { get; set; }
        public Nullable<bool> canadd { get; set; }
        public Nullable<bool> canedit { get; set; }
        public Nullable<bool> candelete { get; set; }
        public Nullable<int> adddby { get; set; }
        public Nullable<System.DateTime> addon { get; set; }
        public Nullable<int> modby { get; set; }
        public Nullable<System.DateTime> modon { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
    }
}
