//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarn_Add_Budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarn_Add_Budget()
        {
            this.Trans_Salary = new HashSet<Trans_Salary>();
        }
    
        public int Bgt_Id { get; set; }
        public Nullable<int> Head_Id { get; set; }
        public Nullable<int> SubHead_Id { get; set; }
        public Nullable<int> InnerSubHead_ID { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<bool> Bit_Approved { get; set; }
        public Nullable<decimal> Proposed_Re_For_Current { get; set; }
        public Nullable<decimal> Prop_Amnt { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> First_Lvl_Re_For_Current { get; set; }
        public Nullable<decimal> fst_Aprov_Bdgt_Amnt { get; set; }
        public string fst_Arop_Remarks { get; set; }
        public Nullable<bool> fst_Arop_BIT { get; set; }
        public Nullable<decimal> Sec_Lvl_Re_For_Current { get; set; }
        public Nullable<decimal> Sec_Aprov_Bdgt_Amnt { get; set; }
        public string Sec_Arop_Remarks { get; set; }
        public Nullable<bool> Sec_Arop_BIT { get; set; }
        public Nullable<decimal> Bdgt_Amnt { get; set; }
        public string Ho_Remarks { get; set; }
        public Nullable<decimal> Sanc_Amnt { get; set; }
        public Nullable<decimal> Avlb_Amnt { get; set; }
        public Nullable<decimal> Rqst_Adtn_Alt_Amnt { get; set; }
        public Nullable<decimal> Aprv_Adtn_Alt_Amnt { get; set; }
        public Nullable<decimal> Intrm_Bug_Amnt { get; set; }
        public Nullable<decimal> Re_For_Current { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public string Mod_Bug_Amnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trans_Salary> Trans_Salary { get; set; }
    }
}
