//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Revnu_Expenditure_By_Unit
    {
        public int Unit_RevExp_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Head_Id { get; set; }
        public Nullable<int> Subhead_Id { get; set; }
        public Nullable<decimal> Lt_Fy_Exp { get; set; }
        public Nullable<int> Bgt_Id { get; set; }
        public Nullable<decimal> Lb_Pr_Paid { get; set; }
        public Nullable<decimal> Current_expdr { get; set; }
        public Nullable<decimal> Total_Pmt { get; set; }
        public Nullable<decimal> Prob_Exp { get; set; }
        public Nullable<decimal> Total_Prop_Exp { get; set; }
        public Nullable<decimal> Fst_Bdgt_Nxt_Fy { get; set; }
        public string Fst_remarks { get; set; }
        public string Fst_Prop_Re_Curnt { get; set; }
        public Nullable<bool> fst_Arop_BIT { get; set; }
        public Nullable<bool> Sec_Arop_BIT { get; set; }
        public Nullable<decimal> Prop_Re_Curnt { get; set; }
        public Nullable<decimal> Bdgt_Nxt_Fy { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> bit_Second_Aprov { get; set; }
        public Nullable<decimal> Re_For_Current { get; set; }
        public Nullable<decimal> Bdgt_Amnt { get; set; }
        public string Ho_Remarks { get; set; }
        public string FileID { get; set; }
        public Nullable<bool> bit_Aproved { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Modby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
