//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Capital_TPBgt_Prop_By_Unit
    {
        public int TP_Bgt_Unit_Id { get; set; }
        public Nullable<int> Head_Id { get; set; }
        public Nullable<int> SubHead_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Cap_TPbgt_Id { get; set; }
        public string Aprov_No { get; set; }
        public Nullable<System.DateTime> Aprov_Dt { get; set; }
        public Nullable<decimal> Aprov_Est_Cost { get; set; }
        public Nullable<decimal> Lst_Cum_Exp { get; set; }
        public Nullable<decimal> Curnt_Actul_Exp { get; set; }
        public Nullable<decimal> Probl_Exp { get; set; }
        public Nullable<decimal> Total_Exp { get; set; }
        public Nullable<decimal> Fst_Bdgt_Nxt_Fy { get; set; }
        public string Fst_remarks { get; set; }
        public Nullable<decimal> Fst_Prop_Re_Curnt { get; set; }
        public Nullable<bool> fst_Arop_BIT { get; set; }
        public Nullable<bool> Sec_Arop_BIT { get; set; }
        public Nullable<decimal> Prop_Re_Curnt { get; set; }
        public Nullable<bool> bit_Second_Aprov { get; set; }
        public Nullable<decimal> Re_For_Current { get; set; }
        public Nullable<decimal> Prop_BE_NxtFy { get; set; }
        public Nullable<decimal> Aprov_Bgt { get; set; }
        public string Remarks { get; set; }
        public string Ho_Remarks { get; set; }
        public Nullable<bool> bit_Aproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public Nullable<int> Modby { get; set; }
    }
}
