//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_RequsitionNumber
    {
        public int Req_NumberId { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public string Req_Num { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public Nullable<System.DateTime> ModBy { get; set; }
    
        public virtual Mst_Unit Mst_Unit { get; set; }
    }
}
