//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Salary
    {
        public int Salary_Id { get; set; }
        public Nullable<int> SubHead_Id { get; set; }
        public Nullable<int> monthid { get; set; }
        public Nullable<int> Bgt_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<decimal> Req_Amount { get; set; }
        public Nullable<decimal> Pf { get; set; }
        public Nullable<decimal> Gsli { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> ReductionRtainByHo { get; set; }
        public Nullable<decimal> DeductionRealsedtoUnit { get; set; }
        public Nullable<bool> bit_Approve { get; set; }
        public Nullable<decimal> ApproveAmountByHo { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
    
        public virtual Financial_Year Financial_Year { get; set; }
        public virtual Mst_month Mst_month { get; set; }
        public virtual Mst_Unit Mst_Unit { get; set; }
        public virtual Tarn_Add_Budget Tarn_Add_Budget { get; set; }
    }
}
