//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Cap_Wrk_CashRequistionInvoice
    {
        public int Cptl_Wrk_CashReq_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Cap_Work_Bgt_Id { get; set; }
        public Nullable<System.DateTime> Req_Date { get; set; }
        public string Req_Num { get; set; }
        public Nullable<decimal> Cur_bnk_Balance { get; set; }
        public Nullable<decimal> Cur_csh_Balance { get; set; }
        public string ReasonCash_Maintain { get; set; }
        public Nullable<int> bnkid { get; set; }
        public Nullable<int> Bnk_DtlsId { get; set; }
        public string Created_By { get; set; }
        public string Checked_By { get; set; }
        public string Authorized_By { get; set; }
        public string Invoice_Type { get; set; }
        public string Invoice_Catagory { get; set; }
        public Nullable<int> Cap_Wok_Head_Id { get; set; }
        public string SupplierName { get; set; }
        public string Purchased_MaterialDesc { get; set; }
        public string wopoNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDt { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public Nullable<decimal> It_Tds { get; set; }
        public Nullable<decimal> Igst_Td { get; set; }
        public Nullable<decimal> Cgst_Tds { get; set; }
        public Nullable<decimal> Sgst_Tds { get; set; }
        public Nullable<decimal> Obroc_Tds { get; set; }
        public Nullable<decimal> Royality_Tds { get; set; }
        public Nullable<decimal> DeductedTds { get; set; }
        public Nullable<decimal> Other_Deduction { get; set; }
        public Nullable<decimal> Retain_Amt { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public string DivisonOfficer_Comment { get; set; }
        public string Ho_Initator { get; set; }
        public string Ho_AprovedLevel1 { get; set; }
        public string Final_approver { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
    }
}
