//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Cap_Work_Bgt_Requsion_Unit
    {
        public int Cap_Work_Bgt_Req_Id { get; set; }
        public Nullable<int> Cap_Wok_Head_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> Cap_Work_Bgt_Id { get; set; }
        public Nullable<decimal> Lst_Cum_Exp { get; set; }
        public Nullable<decimal> Curnt_Actul_Exp { get; set; }
        public Nullable<decimal> Probl_Exp { get; set; }
        public Nullable<decimal> Total_Exp { get; set; }
        public Nullable<decimal> Aprov_Bgt { get; set; }
        public Nullable<decimal> Prop_Re_Curnt { get; set; }
        public Nullable<decimal> Re_For_Current { get; set; }
        public string Ho_Remarks { get; set; }
        public Nullable<bool> Bit_Aprove { get; set; }
        public Nullable<decimal> Prop_BE_NxtFy { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public Nullable<int> Modby { get; set; }
    }
}
