//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Cap_Work_Budget
    {
        public int Cap_Work_Bgt_Id { get; set; }
        public Nullable<int> Cap_Wok_Head_Id { get; set; }
        public Nullable<int> Fin_Id { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<decimal> Prop_Amnt { get; set; }
        public Nullable<decimal> Bdgt_Amnt { get; set; }
        public Nullable<decimal> Avlb_Amnt { get; set; }
        public Nullable<decimal> Rqst_Adtn_Alt_Amnt { get; set; }
        public Nullable<decimal> Aprv_Adtn_Alt_Amnt { get; set; }
        public Nullable<decimal> Mod_Bug_Amnt { get; set; }
        public Nullable<decimal> Re_For_Current { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Cry_Nxt_Fy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddOn { get; set; }
        public Nullable<int> AddBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public Nullable<int> ModBy { get; set; }
        public string FileID { get; set; }
    }
}
