//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trns_Chng_Pwd_Log
    {
        public int Cp_Id { get; set; }
        public Nullable<int> Usr_Id { get; set; }
        public string OTP { get; set; }
        public Nullable<int> Modby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
    }
}
